set nocompatible
autocmd!

filetype plugin on
syntax on

runtime macros/matchit.vim

set autoindent
set backspace=indent,eol,start
set backupdir=~/.vim/tmp/backup
set dir=~/.vim/tmp/swap
set encoding=utf-8
set expandtab
set exrc
set hidden
set history=1000
set hlsearch
set incsearch
set iskeyword+=-
set laststatus=2
set number
set scrolloff=3
set shell=/bin/bash
set shiftwidth=2
set showcmd
set showmode
set smarttab
set softtabstop=2
set tabstop=2
set undodir=~/.vim/tmp/undo
set visualbell
set wildmode=list:longest
set wildmenu
set path+=**

let mapleader = " "

nnoremap <leader>g :e %:.:h/
nnoremap <leader>c :saveas %:p:h/

nnoremap <C-e> 4<C-e>
nnoremap <C-y> 4<C-y>

nnoremap <C-l> :noh<CR>
nnoremap <leader>f :find<space>
nnoremap <leader>b :ls<CR>:b<space>

silent execute '!mkdir -p $HOME/.vim/tmp/backup'
silent execute '!mkdir -p $HOME/.vim/tmp/swap'
silent execute '!mkdir -p $HOME/.vim/tmp/undo'
